name: Release

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 9.*

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
            dotnet pack -c release -o nuget -p:Version=1.0.0.${{github.run_number}}
            dotnet nuget push "nuget\*.nupkg" --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
        
        