name: Release
on:
  workflow_dispatch:
    branches: [ master ]


jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 6.0.x

      - name: Build
        run: |
            sed -i "s/\(<Version>\([0-9]\+\.\)\{3\}\)\([0-9]\+\)/\1${{github.run_number}}/" "FontIconsLib/FontIconsLib.csproj"
            dotnet build -c release
            dotnet pack -c release -o nuget
            dotnet nuget push "nuget/*.nupkg" --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
        
        